// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRyltfmhQi2V0HAx0IGd798b_-8H0WIS8',
    appId: '1:14520324998:web:a383a31f85149dd1f55207',
    messagingSenderId: '14520324998',
    projectId: 'tatame-plus',
    authDomain: 'tatame-plus.firebaseapp.com',
    storageBucket: 'tatame-plus.firebasestorage.app',
    measurementId: 'G-X1Y7ZHJFH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0WUYiEYEmBxwqABoKj8YG5k2whndIVM8',
    appId: '1:14520324998:android:eccfb97a205b84ddf55207',
    messagingSenderId: '14520324998',
    projectId: 'tatame-plus',
    storageBucket: 'tatame-plus.firebasestorage.app',
  );
}
